name: FactionChat
softdepend: [Factions, BanManager, bPermissions, GroupManager, PermissionsEx, AuthMe, Essentials, Vault]
main: nz.co.lolnet.james137137.FactionChat.FactionChat
version: ${project.version}
authors: [James Anderson]
commands:
  fchat:
    description: Main command to switch Chat Mode
    usage: /<command> [option]
    aliases: [fc]
  fchato:
    description: Send a message to any Factions
    usage: /<command> <FactionName> <Message> 
    aliases: [fco]
  fchatf:
    description: Send a Faction message
    usage: /<command> <Message> 
    aliases: [ff]
  fchatat:
    description: Send a Ally and Truce message
    usage: /<command> <Message> 
    aliases: [fat]
  fchata:
    description: Send a Ally message
    usage: /<command> <Message> 
    aliases: [fa]
  fchatt:
    description: Send a Truce message
    usage: /<command> <Message> 
    aliases: [ft]
  fchate:
    description: Send a Enemy message
    usage: /<command> <Message> 
    aliases: [fe]
  fchatad:
    description: Send a admin message
    usage: /<command> <Message> 
    aliases: [fad]
  fchatm:
    description: Send a moderator message
    usage: /<command> <Message> 
    aliases: [fm]
  fchatua:
    description: Send a moderator message
    usage: /<command> <Message> 
    aliases: [fcu]
  fcadmin:
    description: admin commands to print info and change player chatmode
    usage: /<command> <info/change> <playername> <option>
       
permissions:
  factionchat.*:
    description: gives access to all factionchat commands
    default: op
    children:
      factionchat.spy: true
      factionchat.adminchat: true
      factionchat.update: true
      factionchat.otherchat: true
      factionchat.enemychat: true
      factionchat.admins: true
      factionchat.mutebypass: true
      factionchat.localchatbypass.publicsend: true
      factionchat.localchatbypass.publicreceive: true
      factionchat.localchatbypass.channelsend: true
      factionchat.localchatbypass.channelreceive: true
  factionchat.factionchat:
    description: allows player to send and receive messages from their factions.
    default: true
  factionchat.allychat:
    description: allows player to send and receive messages from their ally factions
    default: true
  factionchat.trucechat:
    description: allows player to send and receive messages from their truce factions
    default: true  
  factionchat.command.mutepublic:
     description: allows player run command /fc mute or /fc mutepublic
     default: true
  factionchat.command.muteally:
     description: allows player run command /fc muteally
     default: true
  factionchat.command.muteplayer:
     description: allows player run command /fc muteplayer
     default: op
  factionchat.chat.colour:
    description: allows player to use colour in chat
    default: op
  factionchat.otherchat:
    description: allows player to send messages to other factions
    default: op
  factionchat.enemychat:
    description: allows player to use enemy chat.
    default: op    
  factionchat.admin.info:
    description: allows player to display infomation of a player
    default: op
  factionchat.admin.change:
    description: allows player to change chat mode of the target player
    default: op
  factionchat.spy:
    description: allows player to see all faction,ally,enemy,and other chat
    default: op
  factionchat.vipchat:
    description: allows player to see and use vip chat
    default: op
  factionchat.userassistantchat:
    description: allows player to see and use userassistant chat
    default: op
    children:
      factionchat.vipchat: true
  factionchat.jrmodchat:
    description: allows player to see and use jrmoderator chat
    default: op
    children:
      factionchat.userassistantchat: true
  factionchat.modchat:
    description: allows player to see and use moderator chat
    default: op
    children:
      factionchat.jrmodchat: true
  factionchat.srmodchat:
    description: allows player to see and use srmoderator chat
    default: op
    children:
      factionchat.jrmodchat: true
      factionchat.modchat: true
  factionchat.jradminchat:
    description: allows player to see and use jradministrator chat
    default: op
    children:
      factionchat.jrmodchat: true
      factionchat.modchat: true
      factionchat.srmodchat: true
  factionchat.adminchat:
    description: allows player to see and use administrator chat
    default: op
    children:
      factionchat.jrmodchat: true
      factionchat.modchat: true
      factionchat.srmodchat: true
      factionchat.jradminchat: true
  factionchat.update:
    description: allows player to check and update this plugin
    default: op
  factionchat.reload:
    description: allows player to reload plugin
    default: op
  factionchat.mutebypass:
    description: allows staff to bypass publicmute and send messages to all players
    default: op
  factionchat.localchat.command:
    description: allows players to swich to/from localchat on themself
    default: op
  factionchat.localchatbypass.publicsend:
    description: allows staff to bypass localchat and send messages to all players no matter what distance
    default: op
  factionchat.localchatbypass.publicreceive:
    description: allows staff to bypass localchat and receive messages from all players no matter what distance
    default: op
  factionchat.localchatbypass.channelsend:
    description: allows staff to bypass localchat faction channel and send messages to all players no matter what distance
    default: op
  factionchat.localchatbypass.channelreceive:
    description: allows staff to bypass localchat faction channel and receive messages from all players no matter what distance
    default: op